version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_auth_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fintrack_db
      MYSQL_USER: fintrack_admin
      MYSQL_PASSWORD: Vicente5150.
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - db_data:/var/lib/mysql

  auth_service:
    build: .
    container_name: ms-auth-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://fintrack_admin:Vicente5150.@db:3306/fintrack_db
      USER_SERVICE_URL: ${USER_SERVICE_URL:-http://host.docker.internal:8000}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY:-fintruck-internal}
      SECRET_KEY: ${SECRET_KEY:-change-this-secret}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    ports:
      - "8001:8000"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:
